"""Check-time stub for the numpy surface TONECRAFT's DSP uses.

Jac's checker cannot resolve numpy's own shipped stubs, which leaves every
array expression as `<Unknown>` and blocks it at the next typed boundary. This
file is the guide-sanctioned "type the source" fix: it is consumed only by
`jac check`, while `import numpy as np` still binds the real package at
runtime. Extend it when the engine reaches for a new numpy call.
"""

from typing import Any

class ndarray:
    shape: tuple[int, ...]
    dtype: Any
    size: int
    ndim: int
    def __len__(self) -> int: ...
    def __iter__(self) -> Any: ...
    def __getitem__(self, key: Any) -> ndarray: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
    def __neg__(self) -> ndarray: ...
    def __abs__(self) -> ndarray: ...
    def __add__(self, other: Any) -> ndarray: ...
    def __radd__(self, other: Any) -> ndarray: ...
    def __sub__(self, other: Any) -> ndarray: ...
    def __rsub__(self, other: Any) -> ndarray: ...
    def __mul__(self, other: Any) -> ndarray: ...
    def __rmul__(self, other: Any) -> ndarray: ...
    def __truediv__(self, other: Any) -> ndarray: ...
    def __rtruediv__(self, other: Any) -> ndarray: ...
    def __pow__(self, other: Any) -> ndarray: ...
    def __mod__(self, other: Any) -> ndarray: ...
    def __gt__(self, other: Any) -> ndarray: ...
    def __ge__(self, other: Any) -> ndarray: ...
    def __lt__(self, other: Any) -> ndarray: ...
    def __le__(self, other: Any) -> ndarray: ...
    def __eq__(self, other: Any) -> ndarray: ...
    def __ne__(self, other: Any) -> ndarray: ...
    def __and__(self, other: Any) -> ndarray: ...
    def __or__(self, other: Any) -> ndarray: ...
    def __invert__(self) -> ndarray: ...
    def __float__(self) -> float: ...
    def __int__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __index__(self) -> int: ...
    def astype(self, dt: Any) -> ndarray: ...
    def tolist(self) -> list[Any]: ...
    def tobytes(self) -> bytes: ...
    def copy(self) -> ndarray: ...
    def ravel(self) -> ndarray: ...
    def reshape(self, *args: Any) -> ndarray: ...
    def mean(self, axis: Any = ...) -> ndarray: ...
    def sum(self, axis: Any = ...) -> ndarray: ...
    def max(self, axis: Any = ...) -> ndarray: ...
    def min(self, axis: Any = ...) -> ndarray: ...
    def std(self, axis: Any = ...) -> ndarray: ...

float32: Any
float64: Any
int8: Any
int16: Any
int32: Any
int64: Any
nan: float
pi: float
newaxis: Any

class _StrideTricks:
    @staticmethod
    def sliding_window_view(x: Any, window_shape: Any, axis: Any = ...) -> ndarray: ...

class _Lib:
    stride_tricks: _StrideTricks

lib: _Lib

class _Fft:
    @staticmethod
    def rfft(a: Any, n: Any = ..., axis: Any = ...) -> ndarray: ...
    @staticmethod
    def irfft(a: Any, n: Any = ..., axis: Any = ...) -> ndarray: ...
    @staticmethod
    def rfftfreq(n: Any, d: Any = ...) -> ndarray: ...

fft: _Fft

class _Random:
    @staticmethod
    def normal(loc: Any = ..., scale: Any = ..., size: Any = ...) -> ndarray: ...
    @staticmethod
    def seed(s: Any) -> None: ...

random: _Random

def array(obj: Any, dtype: Any = ...) -> ndarray: ...
def asarray(obj: Any, dtype: Any = ...) -> ndarray: ...
def ascontiguousarray(obj: Any, dtype: Any = ...) -> ndarray: ...
def frombuffer(buf: Any, dtype: Any = ...) -> ndarray: ...
def zeros(shape: Any, dtype: Any = ...) -> ndarray: ...
def ones(shape: Any, dtype: Any = ...) -> ndarray: ...
def full(shape: Any, fill_value: Any, dtype: Any = ...) -> ndarray: ...
def empty(shape: Any, dtype: Any = ...) -> ndarray: ...
def arange(start: Any, stop: Any = ..., step: Any = ..., dtype: Any = ...) -> ndarray: ...
def linspace(start: Any, stop: Any, num: Any = ...) -> ndarray: ...
def copy(a: Any) -> ndarray: ...
def pad(a: Any, pad_width: Any, mode: Any = ..., **kwargs: Any) -> ndarray: ...
def concatenate(arrs: Any, axis: Any = ...) -> ndarray: ...
def stack(arrs: Any, axis: Any = ...) -> ndarray: ...
def expand_dims(a: Any, axis: Any) -> ndarray: ...
def ravel(a: Any) -> ndarray: ...
def compress(condition: Any, a: Any, axis: Any = ...) -> ndarray: ...
def take(a: Any, indices: Any, axis: Any = ...) -> ndarray: ...
def take_along_axis(a: Any, indices: Any, axis: Any) -> ndarray: ...
def flatnonzero(a: Any) -> ndarray: ...
def nonzero(a: Any) -> Any: ...
def where(cond: Any, x: Any = ..., y: Any = ...) -> ndarray: ...
def clip(a: Any, a_min: Any, a_max: Any) -> ndarray: ...
def diff(a: Any, axis: Any = ..., prepend: Any = ..., append: Any = ...) -> ndarray: ...
def gradient(a: Any, *varargs: Any) -> ndarray: ...
def cumsum(a: Any, axis: Any = ...) -> ndarray: ...
def sort(a: Any, axis: Any = ...) -> ndarray: ...
def argmax(a: Any, axis: Any = ...) -> ndarray: ...
def argmin(a: Any, axis: Any = ...) -> ndarray: ...
def argsort(a: Any, axis: Any = ...) -> ndarray: ...
def interp(x: Any, xp: Any, fp: Any) -> ndarray: ...
def polyfit(x: Any, y: Any, deg: Any) -> ndarray: ...
def corrcoef(x: Any, y: Any = ...) -> ndarray: ...
def hanning(m: Any) -> ndarray: ...
def hamming(m: Any) -> ndarray: ...
def real(a: Any) -> ndarray: ...
def imag(a: Any) -> ndarray: ...
def conj(a: Any) -> ndarray: ...
def abs(a: Any) -> ndarray: ...
def square(a: Any) -> ndarray: ...
def sqrt(a: Any) -> ndarray: ...
def power(a: Any, b: Any) -> ndarray: ...
def sin(a: Any) -> ndarray: ...
def cos(a: Any) -> ndarray: ...
def exp(a: Any) -> ndarray: ...
def log(a: Any) -> ndarray: ...
def log2(a: Any) -> ndarray: ...
def log10(a: Any) -> ndarray: ...
def sign(a: Any) -> ndarray: ...
def isnan(a: Any) -> ndarray: ...
def isfinite(a: Any) -> ndarray: ...
def nan_to_num(a: Any, nan: Any = ..., posinf: Any = ..., neginf: Any = ...) -> ndarray: ...
def greater(a: Any, b: Any) -> ndarray: ...
def greater_equal(a: Any, b: Any) -> ndarray: ...
def less(a: Any, b: Any) -> ndarray: ...
def less_equal(a: Any, b: Any) -> ndarray: ...
def equal(a: Any, b: Any) -> ndarray: ...
def not_equal(a: Any, b: Any) -> ndarray: ...
def logical_and(a: Any, b: Any) -> ndarray: ...
def logical_or(a: Any, b: Any) -> ndarray: ...
def logical_not(a: Any) -> ndarray: ...
def maximum(a: Any, b: Any) -> ndarray: ...
def minimum(a: Any, b: Any) -> ndarray: ...
def mean(a: Any, axis: Any = ..., keepdims: Any = ...) -> ndarray: ...
def median(a: Any, axis: Any = ...) -> ndarray: ...
def nanmedian(a: Any, axis: Any = ...) -> ndarray: ...
def nanmean(a: Any, axis: Any = ...) -> ndarray: ...
def std(a: Any, axis: Any = ...) -> ndarray: ...
def var(a: Any, axis: Any = ...) -> ndarray: ...
def sum(a: Any, axis: Any = ...) -> ndarray: ...
def prod(a: Any, axis: Any = ...) -> ndarray: ...
def max(a: Any, axis: Any = ...) -> ndarray: ...
def min(a: Any, axis: Any = ...) -> ndarray: ...
def percentile(a: Any, q: Any, axis: Any = ...) -> ndarray: ...
def all(a: Any, axis: Any = ...) -> ndarray: ...
def any(a: Any, axis: Any = ...) -> ndarray: ...
def count_nonzero(a: Any, axis: Any = ...) -> int: ...
def unwrap(p: Any) -> ndarray: ...
